name: final_year_project2024
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4 # Downgraded to be compatible with http ^0.13.3
  shared_preferences: ^2.3.2
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  intl: ^0.17.0
  image_picker: ^1.1.2
  http: ^0.13.3 # Compatible with gallery_saver ^2.3.2
  gallery_saver: ^2.3.2
  permission_handler: ^11.3.1
  fl_chart: ^0.68.0
  provider: ^6.0.3
  url_launcher: ^6.1.0
  flutter_local_notifications: ^9.1.4
  webview_flutter: ^2.0.13
  mysql1: ^0.19.2
  carousel_slider:
  flutter_plugin_android_lifecycle: ^2.0.22
  camera_android_camerax: ^0.6.8+2





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cinnamon_logo.png
    - assets/images/record1.jpg
    - assets/images/record2.jpg
    - assets/images/record3.jpg
    - assets/images/record4.jpg
    - assets/images/record5.jpg
    - assets/images/cinnamon.png
    - assets/images/cinnamon11.png
    - assets/images/Load4.png
    - assets/images/cinnamon2.png
    - assets/images/cinnamon3.png
    - assets/images/cinnamon4.png
    - assets/images/cinnamon6.png
    - assets/images/cinnamon09.png
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/cin.jpg
    - assets/images/abc.jpg
    - assets/images/Cinno.jpg
    - assets/images/cin2.png


